// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qewuorfsbdcakfraxlev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFld3VvcmZzYmRjYWtmcmF4bGV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNTI2MzEsImV4cCI6MjA3OTkyODYzMX0.bONmcHdFpRiwBxLTX9E78GUAjDu4JeF5SQWJeCRedfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});